[project]
name = "Asteroids"
version = "0.1.0"
description = "With your spaceship you should destroy the Asteroids, or you will get killed"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
